import {defineArrayMember, defineField} from 'sanity'

const pageBlockTypes = [
  'homeHeroBlock',
  'pageHeroBlock',
  'splitIntroBlock',
  'editorialPrinciplesBlock',
  'metricsBandBlock',
  'problemSolutionBlock',
  'textBlock',
  'featuredServicesBlock',
  'featuredProjectsBlock',
  'iconCardsBlock',
  'partnersBlock',
  'logoCardGridBlock',
  'googleReviewsBlock',
  'reviewShowcaseBlock',
  'contactFormBlock',
  'aboutIntroBlock',
  'aboutTeamBlock',
  'aboutTeamImageBlock',
  'teamProfilesShowcaseBlock',
  'visitInvitationBlock',
  'splitTimelineBlock',
  'faqAnswersGridBlock',
  'projectsShowcaseGridBlock',
  'stackedStepsListBlock',
  'splitFeatureListBlock',
  'darkAssuranceGridBlock',
  'centeredActionBannerBlock',
  'processBlock',
  'processFaqBlock',
  'processIntakeBannerBlock',
  'businessContentBlock',
  'videoChecklistBlock',
] as const

export const contentBlocksField = defineField({
  name: 'contentBlocks',
  title: 'Page Builder',
  type: 'array',
  description: 'Build this page with reusable content sections.',
  of: pageBlockTypes.map((type) => defineArrayMember({type})),
  options: {
    insertMenu: {
      groups: [
        {
          name: 'hero',
          title: 'Hero Sections',
          of: ['homeHeroBlock', 'pageHeroBlock', 'splitIntroBlock'],
        },
        {
          name: 'supporting',
          title: 'Supporting Sections',
          of: ['metricsBandBlock', 'editorialPrinciplesBlock'],
        },
        {
          name: 'content',
          title: 'Content Sections',
          of: [
            'textBlock',
            'problemSolutionBlock',
            'aboutIntroBlock',
            'aboutTeamBlock',
            'aboutTeamImageBlock',
            'teamProfilesShowcaseBlock',
            'visitInvitationBlock',
            'splitTimelineBlock',
            'faqAnswersGridBlock',
            'projectsShowcaseGridBlock',
            'stackedStepsListBlock',
            'splitFeatureListBlock',
            'darkAssuranceGridBlock',
            'centeredActionBannerBlock',
            'processBlock',
            'processFaqBlock',
            'processIntakeBannerBlock',
            'businessContentBlock',
            'videoChecklistBlock',
          ],
        },
        {
          name: 'listings',
          title: 'Listings & Cards',
          of: ['featuredServicesBlock', 'featuredProjectsBlock', 'iconCardsBlock'],
        },
        {
          name: 'social',
          title: 'Social Proof',
          of: ['partnersBlock', 'logoCardGridBlock', 'googleReviewsBlock', 'reviewShowcaseBlock'],
        },
        {
          name: 'conversion',
          title: 'CTA & Forms',
          of: ['contactFormBlock', 'centeredActionBannerBlock'],
        },
      ],
      views: [{name: 'grid'}, {name: 'list'}],
    },
  },
})
